### PR TITLE
Add Dockerfile with required settings

### PR DESCRIPTION
**Pull request by skatsaounis**
It addresses (#81)

### CODE REVIEW

**Comment by skatsaounis** [comment]
Hi @furlongm, if you think that this PR can have a future, I can rebase to current develop and tell me your opinion about it. In addition, I have developed a Helm Chart based on this Dockerfile and could also open a subsequent PR.

**Comment by furlongm** [comment]
Rebasing might make it clearer what's in the PR. I also have a Dockerfile that I was going to add in v2, and there a couple of others I know. Wondering if it might be sensible to just link to the various Dockerfiles rather than have one in the project?

**Comment by skatsaounis** [comment]
@furlongm I proceeded with the rebase. As you can see, the Dockerfile assumes that Patchman runs in Python2. If you are ready to make the transition to 3, it can be upgraded.

**Comment by skatsaounis** [comment]
@furlongm Hi Marcus. Did you have the chance to take a look here? This acts as a kind reminder.

**Pull request closed without merging**
